//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cabinet_ProjectEntities1 : DbContext
    {
        public Cabinet_ProjectEntities1()
            : base("name=Cabinet_ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministratorsSet> AdministratorsSet { get; set; }
        public virtual DbSet<SchoolSubjectsSet> SchoolSubjectsSet { get; set; }
        public virtual DbSet<TeachersSet> TeachersSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
