//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolSubjectsSet
    {
        public int Id { get; set; }
        public string NameSubject { get; set; }
        public int IdTeachers { get; set; }
    
        public virtual TeachersSet TeachersSet { get; set; }
    }
}
